export enum BookCategory {
  GENERAL_WORK = "000",
  PHILOSOPHY_AND_PSYCHOLOGY = "100",
  RELIGION = "200",
  SOCIAL_SCIENCES = "300",
  LANGUAGE = "400",
  NATUAL_SCIENCES_AND_MATHEMATICS = "500",
  TECHNOLOGY_AND_APPLIED_SCIENCES = "600",
  ARTS_AND_RECREATION = "700",
  LITERATURE = "800",
  HISTORY_AND_GEOGRAPHY = "900",
}
