@startuml
left to right direction

:Guest User: as gUser
:Logged In User: as lUser
:Client: as client
:Admin: as admin

rectangle "Book Management System" {
  usecase "Register" as register
  usecase "Login" as login
  usecase "Logout" as logout

  'For Logged In Users
  usecase "Get Book List" as gBookList
  usecase "Filter Book By Range of Publish Year" as fRYear
  usecase "Filter Book By Category" as fCategory
  usecase "Filter Book By Availability" as fAvail
  usecase "Search Book" as search

  'For Client
  usecase "Borrow Books" as borrow

  'For Admin
  usecase "Confirm Book Return" as confirmReturn
  usecase "Suspend User Account" as suspendUser
  usecase "Unsuspend User Account" as unsuspendUser
}

lUser <|-- client
lUser <|-- admin

gUser -- register

login .up.> register : extends

lUser -- logout
lUser -- gBookList

search .up.> gBookList : extends

note top of search : Search by id, title, ISBN or publisher

fRYear .up.> search : extends
fCategory .up.> search : extends
fAvail .up.> search : extends

client -- borrow

admin -- confirmReturn
admin -- suspendUser
admin -- unsuspendUser
@enduml
